### ISSUE TITLE
Progress Report Generator Improvements

### ISSUE THREAD

**Issue by RedDevilus** [xTVaser/progress-report-generator#1]
https://xtvaser.github.io/progress-report-generator/

Would be nice to import .md files

Sort PRs lexicographically ascending (oldest PR on top, newest on bottom) instead of newest PRs first

Improve the format of Table of Contents;

Old:
![image](https://user-images.githubusercontent.com/24227051/165562360-699403ce-b693-4432-87cc-0431d6827c7a.png)
New:
![image](https://user-images.githubusercontent.com/24227051/167278074-c61d760b-4271-40a8-90d1-0e04b918f870.png)

Based from https://github.com/PCSX2/pcsx2-net-www/issues/114

**Comment by xTVaser** [comment]
> Would be nice to import .md files

No! 😛 
I would if it was easy to do, but markdown isn't a good data format.  Too annoying to parse.

> Sort PRs lexicographically ascending (oldest PR on top, newest on bottom) instead of newest PRs first

Done in master

> Improve the format of Table of Contents;

Yeah this could be done, I'll do it in the coming days.

**Comment by RedDevilus** [comment]
GUI/Qt is categorised as Other and not GUI:
![image](https://user-images.githubusercontent.com/24227051/165879443-9594d71d-e529-432f-952b-42b800532267.png)

**Comment by xTVaser** [comment]
https://github.com/xTVaser/progress-report-generator/commit/e5878d16e9b8f2e73208f4802e98e7620f25f6dc

- Qt added to defaults
- output should be more like the table of contents example above.
